### ISSUE TITLE
Which language will be used is not clear (DEU vs ENG)

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/tdd_workshop#10]
@henhuy , @gplssm 
Wouldn't non-german speakers attend as well?
If yes I think we should do it in english. 
If no, then we can do it in german. However, the workshop might be reused in the future and it is more likely that everyone understands english. Thus I would be 75% in favor of english (we can still give the oral presentation in german if the audience is only composed of germanophones)

**Comment by henhuy** [comment]
As we discussed - we will use English in slides.
