### ISSUE TITLE
Test requirements not installed automatically

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/tdd_workshop#13]
Hey, just installed miniconda according to your instructions - works out.
However, the [test reqs](https://github.com/rl-institut/tdd_workshop/blob/37cb2beae9e6b79aeccde971d4ea1f43ad32bbaf/tests/test_requirements.txt) flake8 and pylint are not installed when creating the conda env.

Is this intentional?

**Comment by Bachibouzouk** [comment]
There are the tests of the workshop and the tests of the repository for CI. This is ok if people do not have flake8 and pylint :)

Thanks for testing the instructions!
